# Generated by Django 3.1.4 on 2020-12-09 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myartcenter', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artcenter',
        ),
    ]
