# Generated by Django 3.1.4 on 2020-12-10 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myartcenter', '0005_art'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='downloads'),
            preserve_default=False,
        ),
    ]
